# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
#addons:
#  apt:
#    packages:
#      - libxml2-dev
r_binary_packages:
  - r-cran-withr
  - r-cran-httr
  - r-cran-memoise
##  - r-cran-devtools
  #- r-cran-car
  #- r-cran-pbkrtest
  #- r-cran-lme4
  #- r-cran-minqa
  #- r-cran-rcpp
  #- r-cran-nloptr
  #- r-cran-rcppeigen
  #- r-cran-quantreg
  #- r-cran-matrixmodels
  #- r-cran-sparsem
#  - r-cran-data.tree
#  - r-cran-DiagrammeR
  #- r-cran-dplyr
  #- r-cran-assertthat
#  - r-cran-BH
#  - r-cran-bindrcpp
#  - r-cran-bindr
  #- r-cran-plogr
#  - r-cran-glue
  #- r-cran-magrittr
#  - r-cran-pkgconfig
#  - r-cran-rlang
  #- r-cran-tibble
  #- r-cran-htmlwidgets
  #- r-cran-htmltools
  #- r-cran-yaml
  #- r-cran-igraph
  #- r-cran-irlba
  #- r-cran-nmf
  #- r-cran-colorspace
  #- r-cran-doparallel
  #- r-cran-foreach
  #- r-cran-iterators
  #- r-cran-ggplot2
  #- r-cran-gtable
  #- r-cran-lazyeval
  #- r-cran-plyr
  #- r-cran-reshape2
  #- r-cran-stringr
  #- r-cran-stringi
  #- r-cran-scales
  #- r-cran-dichromat
  #- r-cran-labeling
  #- r-cran-munsell
  #- r-cran-rcolorbrewer
  #- r-cran-gridbase
  #- r-cran-pkgmaker
  #- r-cran-registry
  #- r-cran-xtable
  #- r-cran-rngtools
#  - r-cran-influenceR
#  - r-cran-rgexf
#  - r-cran-Rook
  - r-cran-brew
  - r-cran-xml
  - r-cran-viridis
  - r-cran-gridextra
  - r-cran-viridislite
#  - r-cran-visNetwork
#  - r-cran-diptest
  - r-cran-fBasics
  - r-cran-gss
  - r-cran-stabledist
  - r-cran-timedate
  - r-cran-timeseries
#  - r-cran-GGally
  - r-cran-progress
  - r-cran-prettyunits
  - r-cran-reshape
#  - r-cran-ggrepel
#  - r-cran-GPArotation
  - r-cran-knitr
  - r-cran-evaluate
  - r-cran-highr
  - r-cran-markdown
  - r-cran-lavaan
  - r-cran-mnormt
  - r-cran-numderiv
  - r-cran-pbivnorm
  - r-cran-quadprog
#  - r-cran-MBESS
  - r-cran-gsl
#  - r-cran-OpenMx
  - r-cran-mvtnorm
#  - r-cran-rpf
#  - r-cran-StanHeaders
  - r-cran-sem
  - r-cran-matrixcalc
  - r-cran-mi
  - r-cran-arm
  - r-cran-abind
  - r-cran-coda
  - r-cran-semtools
#  - r-cran-mosaic
#  - r-cran-ggdendro
#  - r-cran-latticeextra
#  - r-cran-mosaicData
#  - r-cran-readr
#  - r-cran-hms
  - r-cran-tidyr
#  - r-cran-pander
#  - r-cran-psych
#  - r-cran-pwr
#  - r-cran-rio
  - r-cran-data.table
#  - r-cran-haven
#  - r-cran-openxlsx
