# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#sudo: false
cache: packages

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

### yaml file for ggstatsplot, see
### https://github.com/wibeasley/ggstatsplot/blob/cb454e637995fb381c9d2565f461e582ab59b9b6/.travis.yml

#language: R
#cache: packages
#latex: false
#fortran: true

# Note: http test servers are flaky and we want to minimze false positives
# so we skip examples and vignettes (but not unit tests) on OS X.

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
            
      r_binary_packages:
        - behaviorchange
        - stringi
        - magrittr
        - curl
        - jsonlite
        - Rcpp
        - bindrcpp
        - RcppEigen
        - rpf
        - openssl
        - rlang
        - igraph
        - utf8
        - gss
        - haven
        - XML
        - data.table
        - matrixStats
        - rgl
        - dplyr
        - purrr
        - tidyr
        - readr
        - minqa
        - mvtnorm
        - nloptr
        - SparseM
        - lme4
        - httpuv
        - markdown
        - OpenMx
        - sem  
        - readxl
        - openxlsx
        - pander
        - minpack.lm
        - StanHeaders

        # "These installs will be faster than source installs, but may not always be the most recent version"
        # https://docs.travis-ci.com/user/languages/r/#Additional-Dependency-Fields

#   precise is getting decommissioned on Travis, so better to leave it out
#    - os: linux
#      dist: trusty
#      sudo: false
#      env: R_CODECOV = true
#      r_build_args: '--no-build-vignettes'
#      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode7.3
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libgsl0-dev

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
